---
- name: Install Grafana dependencies
  apt:
    name:
      - software-properties-common
      - apt-transport-https
    state: present
  become: yes

- name: Add Grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  become: yes

- name: Add Grafana repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
  become: yes

- name: Install Grafana
  apt:
    name: grafana
    update_cache: yes
    state: present
  become: yes

- name: Start and enable Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes
  become: yes

- name: Configure Grafana data source
  uri:
    url: "http://localhost:3000/api/datasources"
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    body_format: json
    body:
      name: "Prometheus"
      type: "prometheus"
      url: "http://localhost:9090"
      access: "proxy"
      isDefault: true
  ignore_errors: yes
