---
- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-1.6.1.tar.gz"
  become: yes

- name: Extract Node Exporter
  unarchive:
    src: "/tmp/node_exporter-1.6.1.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/node_exporter-1.6.1.linux-amd64"
  become: yes

- name: Copy Node Exporter binary
  copy:
    src: "/tmp/node_exporter-1.6.1.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: yes
  become: yes

- name: Create Node Exporter systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  become: yes

- name: Start and enable Node Exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
