---
- name: Create prometheus user
  user:
    name: prometheus
    system: yes
    shell: /bin/false
    home: /nonexistent
    create_home: no
  become: yes

- name: Create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus
  become: yes

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-2.45.0.tar.gz"
  become: yes

- name: Extract and install Prometheus
  unarchive:
    src: "/tmp/prometheus-2.45.0.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/prometheus-2.45.0.linux-amd64"
  become: yes

- name: Copy Prometheus binaries
  copy:
    src: "/tmp/prometheus-2.45.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: yes
  loop:
    - prometheus
    - promtool
  become: yes

- name: Template Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
  become: yes

- name: Create Prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  become: yes

- name: Start and enable Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
