---
- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted
  become: yes

- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted
  become: yes

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
  become: yes

- name: restart gpu_exporter
  systemd:
    name: nvidia_gpu_exporter
    state: restarted
  become: yes
